INSERT INTO `users` (`name`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES
('Juan Pérez', 'juan.perez@example.com', 'hashed_password_1', 'admin', NOW(), NOW()),
('María López', 'maria.lopez@example.com', 'hashed_password_2', 'user', NOW(), NOW()),
('Carlos Rodríguez', 'carlos.rodriguez@example.com', 'hashed_password_3', 'user', NOW(), NOW()),
('Ana Gómez', 'ana.gomez@example.com', 'hashed_password_4', 'user', NOW(), NOW()),
('Pedro Sánchez', 'pedro.sanchez@example.com', 'hashed_password_5', 'admin', NOW(), NOW()),
('Laura Torres', 'laura.torres@example.com', 'hashed_password_6', 'user', NOW(), NOW()),
('Miguel Herrera', 'miguel.herrera@example.com', 'hashed_password_7', 'user', NOW(), NOW()),
('Lucía Ramírez', 'lucia.ramirez@example.com', 'hashed_password_8', 'user', NOW(), NOW()),
('Diego Fernández', 'diego.fernandez@example.com', 'hashed_password_9', 'user', NOW(), NOW()),
('Sofía Castro', 'sofia.castro@example.com', 'hashed_password_10', 'user', NOW(), NOW()),
('Fernando Reyes', 'fernando.reyes@example.com', 'hashed_password_11', 'admin', NOW(), NOW()),
('Gabriela Vargas', 'gabriela.vargas@example.com', 'hashed_password_12', 'user', NOW(), NOW()),
('Ricardo León', 'ricardo.leon@example.com', 'hashed_password_13', 'user', NOW(), NOW()),
('Patricia Mendoza', 'patricia.mendoza@example.com', 'hashed_password_14', 'user', NOW(), NOW()),
('Javier Silva', 'javier.silva@example.com', 'hashed_password_15', 'admin', NOW(), NOW());

INSERT INTO `products` (`name`, `stock`, `price`, `created_at`, `updated_at`) VALUES
('Laptop Dell XPS 15', 10, 1500.00, NOW(), NOW()),
('iPhone 15 Pro', 20, 1099.99, NOW(), NOW()),
('Monitor LG UltraGear', 25, 300.00, NOW(), NOW()),
('Teclado Razer BlackWidow', 30, 120.00, NOW(), NOW()),
('Mouse Logitech MX Master 3', 40, 99.99, NOW(), NOW()),
('Audífonos Sony WH-1000XM5', 15, 399.99, NOW(), NOW()),
('Smartwatch Apple Watch Ultra', 18, 799.00, NOW(), NOW()),
('Cámara Nikon D750', 12, 1600.00, NOW(), NOW()),
('Impresora Epson EcoTank', 10, 250.00, NOW(), NOW()),
('Tarjeta Gráfica RTX 4090', 5, 2000.00, NOW(), NOW()),
('Disco SSD NVMe 2TB', 22, 220.00, NOW(), NOW()),
('Memoria RAM Corsair 32GB', 16, 180.00, NOW(), NOW()),
('Silla Gamer Secretlab', 14, 450.00, NOW(), NOW()),
('Router Asus ROG Rapture', 19, 350.00, NOW(), NOW()),
('Procesador AMD Ryzen 9 7950X', 8, 700.00, NOW(), NOW());
